-- Deploy lassi:book to pg

BEGIN;

create table book (

    book_id     int generated by default as identity primary key,
    isbn        text,
    title       text,
    location    text

);


COMMIT;
