-- Deploy lassi:loan to pg
-- requires: book
-- requires: member

BEGIN;

create table loan (

    loan_id     int generated by default as identity primary key,
    member_id   uuid references member,
    book_id     int references book,
    period      daterange

);

COMMIT;
